services:
  - type: web
    name: blog-backend
    runtime: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production 